### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by Pozaza** [parmentf/node-ector#10]
```
TypeError: Cannot read properties of undefined (reading 'id')
    at Ector.generateForward (/home/runner/PozazaykaAI/node_modules/ector/lib/ector.js:185:86)
    at Ector.generateResponse (/home/runner/PozazaykaAI/node_modules/ector/lib/ector.js:290:24)
```
This happens when I use ```ector.generateResponse()``` function

**Comment by Pozaza** [comment]
Fixed
I forgot to check if message.content is null
